### ISSUE TITLE
Add `rzo roles' command to list the roles

### ISSUE THREAD

**Issue by ghoneycutt** [ghoneycutt/rizzo#10]
Would like this behavior to exist so you can easily see the roles that exist without running `rzo config` and piping through jq.

`rzo roles`

output
```
puppetmaster
web
app
db
log
```

**Comment by ghoneycutt** [comment]
@jeffmccune could you please look into this

**Comment by jeffmccune** [comment]
Sure thing

**Comment by ghoneycutt** [comment]
Released in v0.4.0
