### ISSUE TITLE
Switch to YAML instead of JSON

### ISSUE THREAD

**Issue by ghoneycutt** [ghoneycutt/rizzo#32]
We should be using YAML as it allows for comments and JSON does not.

**Comment by ghoneycutt** [comment]
@treydock could you please have a look

**Comment by treydock** [comment]
@ghoneycutt Ya I'll take a look.  Should there be any kind of backwards compatibility or migration path or just a major bump in version and expect people to convert JSON to YAML?

**Comment by ghoneycutt** [comment]
We are still pre 1.0.0 so breaking changes are OK. Please write a simple script that loads in JSON data and returns YAML and we'll use that to make the migration easy.
