### ISSUE TITLE
Ensure that options with the value `nil` are not added to Vagrantfile

### ISSUE THREAD

**Issue by ghoneycutt** [ghoneycutt/rizzo#35]
If a value is `nil` it will be incorrectly added with a line such as

`"box_url": = nil`

when it should just not add the config option.

**Comment by ghoneycutt** [comment]
@treydock could you please look into this

note, you can specify nil in YAML as `null` and `~`

**Comment by treydock** [comment]
Should the solution be to omit `null` and `~` values or should the validation be updated to be more strict?  It appears like the template doesn't check all keys for existence of keys like `box` and `box_url` are added to Vagrantfile regardless of value.

**Comment by ghoneycutt** [comment]
If a config's value is null, then the item should not be in the config at all. box_url and checksum come to mind because you can specify a box name that is from the community or a json file that has that information already in it. We'll need to modify the template to make the configs optional.

**Comment by treydock** [comment]
Added commit to #34 that fixes this.  I wanted to add some fixtures and figured easier to use YAML than have JSON and potential merge conflicts.

**Comment by ghoneycutt** [comment]
@treydock Is this completed or do we need more work / testing on this?

**Comment by treydock** [comment]
The actual box can still end up `nil`, so not entirely done.  I'll open separate issue to track that issue since a bit more involved than just not allowing `nil`.

**Comment by treydock** [comment]
Looks like `hostname` can end up nil, will fix.
